name: "gitub-sha"

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the commit SHA
        run: echo ${{ github.sha }}
